apiVersion: composition.krateo.io/v0-1-0
kind: NginxRedisServer
metadata:
  name: nginx-redis-composition-1
  namespace: default
spec:
  image:
    repository: nginx
    tag: "1.25.3"
  service:
    type: ClusterIP
  redis:
    image:
      repository: redis
      tag: "7.2.4"
